# Generated by Django 3.2.13 on 2022-05-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozio_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geojson',
            old_name='jeojson',
            new_name='geojson',
        ),
    ]
